import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const attrTypeValidator = v.union(
  v.literal("string"),
  v.literal("number"),
  v.literal("boolean"),
);

const metadataValueValidator = v.union(
  v.string(),
  v.number(),
  v.boolean(),
  v.null(),
);

export default defineSchema({
  runtimeRegistrations: defineTable({
    runtime: v.string(),
    description: v.optional(v.string()),
    historyStreamType: v.string(),
    factEntities: v.array(
      v.object({
        entityType: v.string(),
        states: v.array(v.string()),
        attrs: v.record(v.string(), attrTypeValidator),
      }),
    ),
    factEdgeKinds: v.array(v.string()),
    factPartitions: v.array(v.string()),
    factsNamespaceSuffix: v.string(),
    currentNamespaceSuffix: v.string(),
    historicalNamespaceSuffix: v.string(),
    currentSourceKinds: v.optional(v.array(v.string())),
    historicalSourceKinds: v.optional(v.array(v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_runtime", ["runtime"]),

  runtimeStreams: defineTable({
    runtime: v.string(),
    streamId: v.string(),
    factsNamespace: v.string(),
    currentNamespace: v.string(),
    historicalNamespace: v.string(),
    latestVersion: v.number(),
    latestEntryId: v.optional(v.string()),
    latestEntryTime: v.optional(v.number()),
    latestEntity: v.optional(v.string()),
    lastCommitKey: v.optional(v.string()),
    lastWorkId: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_runtime_stream", ["runtime", "streamId"])
    .index("by_runtime_lastWorkId", ["runtime", "lastWorkId"]),

  runtimeCommitLog: defineTable({
    runtime: v.string(),
    streamId: v.string(),
    commitKey: v.string(),
    workId: v.optional(v.string()),
    state: v.union(
      v.literal("queued"),
      v.literal("running"),
      v.literal("completed"),
      v.literal("failed"),
      v.literal("canceled"),
    ),
    attempts: v.number(),
    error: v.optional(v.string()),
    entryId: v.optional(v.string()),
    sourceVersion: v.optional(v.number()),
    entryTime: v.optional(v.number()),
    currentKey: v.optional(v.string()),
    historicalKey: v.optional(v.string()),
    payload: v.optional(v.record(v.string(), metadataValueValidator)),
    queuedAt: v.optional(v.number()),
    startedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index("by_runtime_stream_commitKey", ["runtime", "streamId", "commitKey"])
    .index("by_workId", ["workId"]),

  memoryCharts: defineTable({
    namespace: v.string(),
    chartKey: v.string(),
    centroid: v.array(v.number()),
    variance: v.array(v.number()),
    radius: v.number(),
    meanDirection: v.array(v.number()),
    sumVector: v.array(v.number()),
    resultantNorm: v.number(),
    tangentVariance: v.number(),
    meanGeodesicResidual: v.number(),
    negativeLogLikelihoodSum: v.number(),
    descriptionLength: v.number(),
    posteriorEvidence: v.number(),
    compressionLoss: v.number(),
    supportCoverageLoss: v.number(),
    overlapPenalty: v.number(),
    coverageEntropy: v.number(),
    preservedInformation: v.number(),
    memberCount: v.number(),
    assignmentCount: v.number(),
    recentAssignmentCount: v.number(),
    boundaryCount: v.number(),
    ambiguityCount: v.number(),
    repartitionEpoch: v.number(),
    repartitionCount: v.number(),
    lastRepartitionAt: v.optional(v.number()),
    lastEvaluationAt: v.optional(v.number()),
    lastDeltaDescriptionLength: v.optional(v.number()),
    lastPosteriorEvidence: v.optional(v.number()),
    sampleEntryId: v.optional(v.string()),
    sampleKey: v.optional(v.string()),
    sampleTitle: v.optional(v.string()),
    sampleSummary: v.optional(v.string()),
    parentChartId: v.optional(v.id("memoryCharts")),
    lastAssignedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_namespace_updatedAt", ["namespace", "updatedAt"])
    .index("by_namespace_chartKey", ["namespace", "chartKey"]),

  memoryChartMembers: defineTable({
    namespace: v.string(),
    chartId: v.id("memoryCharts"),
    entryId: v.string(),
    key: v.string(),
    title: v.optional(v.string()),
    summary: v.string(),
    sourceType: v.union(
      v.literal("text"),
      v.literal("textFile"),
      v.literal("binaryFile"),
    ),
    sourceKind: v.optional(v.string()),
    storageId: v.optional(v.string()),
    mimeType: v.optional(v.string()),
    fileName: v.optional(v.union(v.string(), v.null())),
    metadata: v.optional(v.record(v.string(), metadataValueValidator)),
    embedding: v.array(v.number()),
    geodesicResidual: v.number(),
    localNegativeLogLikelihood: v.number(),
    posteriorProbability: v.number(),
    assignmentEntropy: v.number(),
    supportCoverageLoss: v.number(),
    preservedInformation: v.number(),
    mahalanobisDistance: v.number(),
    ambiguityScore: v.optional(v.number()),
    boundaryScore: v.optional(v.number()),
    repartitionEpoch: v.number(),
    assignedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_namespace_entryId", ["namespace", "entryId"])
    .index("by_chart_assignedAt", ["chartId", "assignedAt"]),

  memoryChartNamespaces: defineTable({
    namespace: v.string(),
    chartCount: v.number(),
    memberCount: v.number(),
    boundaryCount: v.number(),
    ambiguityCount: v.number(),
    negativeLogLikelihoodSum: v.number(),
    descriptionLength: v.number(),
    compressionLoss: v.number(),
    supportCoverageLoss: v.number(),
    overlapPenalty: v.number(),
    coverageEntropy: v.number(),
    preservedInformation: v.number(),
    repartitionCount: v.number(),
    splitCount: v.number(),
    mergeCount: v.number(),
    pendingMaintenanceCount: v.number(),
    lastMaintenanceQueuedAt: v.optional(v.number()),
    lastMaintenanceCompletedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_namespace", ["namespace"]),

  memoryChartSupportEdges: defineTable({
    namespace: v.string(),
    chartPairKey: v.string(),
    fromChartId: v.id("memoryCharts"),
    toChartId: v.id("memoryCharts"),
    supportCount: v.number(),
    overlapMass: v.number(),
    coverageEntropySum: v.number(),
    updatedAt: v.number(),
    createdAt: v.number(),
  })
    .index("by_namespace_pair", ["namespace", "chartPairKey"])
    .index("by_namespace_updatedAt", ["namespace", "updatedAt"]),

  memoryChartRepartitionEvents: defineTable({
    namespace: v.string(),
    kind: v.union(
      v.literal("split"),
      v.literal("merge"),
      v.literal("evaluate"),
    ),
    accepted: v.boolean(),
    targetChartIds: v.array(v.string()),
    resultChartIds: v.array(v.string()),
    deltaDescriptionLength: v.number(),
    posteriorEvidence: v.number(),
    compressionDelta: v.number(),
    supportCoverageDelta: v.number(),
    overlapDelta: v.number(),
    details: v.optional(v.record(v.string(), metadataValueValidator)),
    entryTime: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_namespace_entryTime", ["namespace", "entryTime"]),
});
