/// <reference path="./repo-env.d.ts" />
import path from "node:path";
import { loadMonorepoConfig } from "@agent/config";
import { runDev as runAgentDev } from "../apps/agent/scripts/dev.ts";
import { runDev as runExecutorDev } from "../apps/executor/scripts/dev.ts";
import {
  convexEnvSetInDeployment,
  isConvexProjectConfigured,
  runConvexDev,
} from "./convex.ts";
import { startNgrokStorageTunnel } from "./storageTunnel.ts";

/** Set on the orchestrator process after the nested check so all dev children inherit it. */
const ORCHESTRATOR_CHILD_ENV = "MONOREPO_DEV_ORCHESTRATOR_CHILD";

if (process.env[ORCHESTRATOR_CHILD_ENV] === "1") {
  console.error(
    `${ORCHESTRATOR_CHILD_ENV}=1: refusing to run the monorepo dev orchestrator (would recurse or nest).`,
  );
  process.exit(1);
}

/** Populated during `main()` so `main().catch` can always tear down. */
const devChildren: Bun.Subprocess[] = [];
const tunnelCleanups: Array<() => Promise<void>> = [];

function killAll(children: readonly Bun.Subprocess[]) {
  for (const c of children) {
    try {
      c.kill();
    } catch {
      // ignore
    }
  }
}

async function shutdownAll() {
  killAll(devChildren);
  await Promise.all(tunnelCleanups.map((c) => c()));
}

async function main() {
  process.env[ORCHESTRATOR_CHILD_ENV] = "1";

  devChildren.length = 0;
  tunnelCleanups.length = 0;

  const monorepoRoot = path.join(import.meta.dir, "..");

  const fatal = async (err: unknown) => {
    console.error(err);
    await shutdownAll();
    process.exit(1);
  };
  process.once("uncaughtException", (err) => {
    void fatal(err);
  });
  process.once("unhandledRejection", (err) => {
    void fatal(err);
  });

  try {
    if (!(await isConvexProjectConfigured(monorepoRoot))) {
      console.error(
        "Convex is not configured. Run `bun configure` once from the repo root, then run `bun dev`.",
      );
      process.exit(1);
    }

    const config = loadMonorepoConfig(process.env);

    const { subprocess: convexProc, ready: convexReady } = await runConvexDev({
      appEnv: config.convexDashboard,
      cwd: monorepoRoot,
    });
    devChildren.push(convexProc);
    await convexReady;

    if (config.deferStoragePublicTunnelOrigin) {
      const tunnel = await startNgrokStorageTunnel(process.env);
      tunnelCleanups.push(tunnel.close);
      await convexEnvSetInDeployment({
        cwd: monorepoRoot,
        key: "STORAGE_PUBLIC_TUNNEL_ORIGIN",
        value: tunnel.publicOrigin,
      });
      console.log(
        `Convex env: STORAGE_PUBLIC_TUNNEL_ORIGIN=${tunnel.publicOrigin} (ngrok)`,
      );
    }

    const publicConvexUrl =
      process.env.BUN_PUBLIC_CONVEX_URL?.trim() ||
      process.env.CONVEX_URL?.trim() ||
      "";
    const accountToken = process.env.BUN_PUBLIC_ACCOUNT_TOKEN?.trim() ?? "";
    if (!publicConvexUrl) {
      throw new Error(
        "Missing BUN_PUBLIC_CONVEX_URL / CONVEX_URL after Convex dev ready. If the Convex CLI could not update .env.local, set CONVEX_URL manually to match your local deployment.",
      );
    }
    if (!accountToken) {
      throw new Error(
        "Missing BUN_PUBLIC_ACCOUNT_TOKEN after Convex dev ready (expected in .env.local or generated by ensurePublicEnvInDotenvLocal).",
      );
    }

    const repoEnvFile = path.resolve(monorepoRoot, ".env.local");

    devChildren.push(
      runAgentDev({
        appEnv: {
          HOSTNAME: config.agent.listen.hostname,
          AGENT_LISTEN_HOST: config.agent.listen.hostname,
          AGENT_LISTEN_PORT: String(config.agent.listen.port),
          BUN_PUBLIC_CONVEX_URL: publicConvexUrl,
          BUN_PUBLIC_ACCOUNT_TOKEN: accountToken,
          PORT: String(config.agent.listen.port),
        },
        packageRoot: path.join(monorepoRoot, "apps/agent"),
        repoEnvFile,
      }),
    );
    devChildren.push(
      runExecutorDev({
        appEnv: {
          HOSTNAME: config.executor.listen.hostname,
          EXECUTOR_LISTEN_HOST: config.executor.listen.hostname,
          EXECUTOR_LISTEN_PORT: String(config.executor.listen.port),
          CONVEX_URL: process.env.CONVEX_URL,
          BUN_PUBLIC_CONVEX_URL: publicConvexUrl,
          PORT: String(config.executor.listen.port),
        },
        packageRoot: path.join(monorepoRoot, "apps/executor"),
        repoEnvFile,
      }),
    );
  } catch (err) {
    console.error(err);
    await shutdownAll();
    await Promise.allSettled(devChildren.map((c) => c.exited));
    process.exit(1);
  }

  const firstChildExit = Promise.race(
    devChildren.map(async (c, i) => {
      const code = await c.exited;
      return { i, code } as const;
    }),
  );

  const onSignal = new Promise<"signal">((resolve) => {
    const h = () => resolve("signal");
    process.on("SIGINT", h);
    process.on("SIGTERM", h);
  });

  let outcome: { i: number; code: number } | "signal";
  try {
    outcome = await Promise.race([firstChildExit, onSignal]);
  } catch (err) {
    console.error(err);
    await shutdownAll();
    await Promise.allSettled(devChildren.map((c) => c.exited));
    process.exit(1);
  }

  await shutdownAll();
  await Promise.allSettled(devChildren.map((c) => c.exited));

  if (outcome === "signal") {
    process.exit(0);
  }
  process.exit(outcome.code !== 0 ? outcome.code : 0);
}

main().catch((err) => {
  console.error(err);
  void shutdownAll().then(() => process.exit(1));
});
